"""
SQLAlchemy ORM model for the 'conversation' table.
Only one table is defined as per the project requirements.
"""

from datetime import datetime

from sqlalchemy import Column, Integer, String, Text, DateTime

from app.database.database import Base


class Conversation(Base):
    """
    Stores every human ↔ AI message exchange for a given session.

    Columns:
        id            — Auto-incremented primary key
        session_id    — Groups messages belonging to the same chat session
        human_message — The message sent by the user
        ai_message    — The response generated by the AI agent
        timestamp     — When the exchange happened (defaults to now)
    """

    __tablename__ = "conversation"

    id = Column(Integer, primary_key=True, index=True)
    session_id = Column(String(255), nullable=False, index=True)
    human_message = Column(Text, nullable=False)
    ai_message = Column(Text, nullable=False)
    timestamp = Column(DateTime, default=datetime.utcnow, nullable=False)

    def __repr__(self) -> str:
        return (
            f"<Conversation id={self.id} "
            f"session_id={self.session_id!r} "
            f"timestamp={self.timestamp}>"
        )
